" xdg
source $XDG_CONFIG_HOME/vim/xdg.vim

" encoding
set encoding=utf8

" behaviour
set backspace=indent,start
set clipboard=unnamedplus
set hidden
filetype plugin indent on
runtime macros/matchit.vim

" move cursor to last position when opening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" mappings
let mapleader = "ö"
set pastetoggle=<Leader>p
nnoremap <Leader>r :source $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <Leader>g :edit $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <Leader>t :edit $XDG_CONFIG_HOME/vim/after/ftplugin/<C-r>=&ft<CR>.vim<CR>

" spellchecking
set spellfile=$HOME/.vim/spell/utf-8.add
nnoremap <Leader>s :setlocal spell!<CR>

" search
set ignorecase smartcase
set hlsearch incsearch
nnoremap <Leader>h :nohlsearch<CR>

" tabs
set tabstop=8
set shiftwidth=8
set autoindent

" make
set tags=./tags;,tags;
set autowrite
autocmd QuickFixCmdPost [^l]* cwindow
nnoremap <Leader>m :silent make<CR>G``
nnoremap <Leader>M :w<CR>:new <bar> r!make
nnoremap <Leader>f :copen<CR>
nnoremap <Leader>F :cclose<CR>
nnoremap <Leader>d :cn<CR>
nnoremap <Leader>e :cp<CR>

" interface
set colorcolumn=40,80
set wildmenu
set showcmd
set showfulltag
nnoremap <Leader>n :set number!<CR>

" status line
set laststatus=2
set statusline=%n\ :\ %f%q%r%m%=%l,%c\ %y
nnoremap <Leader>l :set laststatus=

" color
syntax on
let base16colorspace=256
colorscheme tomorrow-night
