#! /bin/sh

# Remove all rules when refreshing
bspc rule -r "*"

# Use DP monitor as main and HDMI as second
mainmonitor="$(bspc query --monitors --names | grep DP | head -n 1)"
secondmonitor="$(bspc query --monitors --names | grep HDMI | head -n 1)"

# Set up workspaces
# bspc monitor $mainmonitor -d    隸
# bspc monitor $mainmonitor -d  ﳘ ﯬ 
# bspc monitor $mainmonitor -d    阮
bspc monitor $mainmonitor -d I II III IV

# If HDMI is connected, set up workspaces on second monitor
# [ ! -z $secondmonitor ] && bspc monitor $secondmonitor -d 冷 露
[ ! -z $secondmonitor ] && bspc monitor $secondmonitor -d V VI

# Set border and gaps
bspc config border_width 10
bspc config window_gap 10

# Remove gaps in monocle mode
bspc config gapless_monocle false
bspc config borderless_monocle false

# Set colors
bspc config normal_border_color "#282828"
bspc config focused_border_color "#d8d8d8"
bspc config active_border_color "#b8b8b8"
bspc config presel_feedback_color "#ab4642"

# Rules for focus and pointer
bspc config focus_follows_pointer false
bspc config click_to_focus any
bspc config swallow_first_click true
bspc config pointer_follows_monitor true

# Scratchpad terminal
bspc rule -a dropdown sticky=on state=floating hidden=on
st -c dropdown -e zsh &

# Window rules
bspc rule -a "Brave-browser" desktop='^3'

# If it isn't running, open spotify on ws 4
[ -z "$(ps -A | grep spotify)" ] && bspc desktop -f ^4 && spotify
bspc desktop -f ^1
