#! /bin/sh

# Remove all rules when refreshing
bspc rule -r "*"

# Use DP monitor as main
mainmonitor="$(bspc query --monitors --names | grep DP | head -n 1)"

# Set up workspaces on main monitor
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

# Set border and gaps
bspc config border_width 10
bspc config window_gap 20

# Set colors
bspc config normal_border_color "#282828"
bspc config focused_border_color "#d8d8d8"
bspc config active_border_color "#b8b8b8"
bspc config presel_feedback_color "#ab4642"

# Rules for focus and pointer
bspc config focus_follows_pointer false
bspc config click_to_focus any
bspc config swallow_first_click true
bspc config pointer_follows_monitor true

# Spawn new windows to the left (?)
bspc config initial_polarity second_child
