;
; Polybar config
;

[colors]
; base16-defualt-dark
base00 = #181818
base01 = #282828
base02 = #383838
base03 = #585858
base04 = #b8b8b8
base05 = #d8d8d8
base06 = #e8e8e8
base07 = #f8f8f8
base08 = #ab4642
base09 = #dc9656
base0A = #f7ca88
base0B = #a1b56c
base0C = #86c1b9
base0D = #7cafc2
base0E = #ba8baf
base0F = #a16946

background = ${colors.base01}
foreground = ${colors.base05}
primary = ${colors.base05}
secondary = ${colors.base0B}
alert = ${colors.base08}

; clock

[bar/clock]
monitor = ${env:MONITOR:DP-4}
width = 274
height = 45
offset-x = 1583
offset-y = 10

fixed-center = true
radius = 12.0

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = monospace:size=25:face=bold;6

modules-center = date

; full bar

[bar/full]
monitor = ${env:MONITOR:DP-4}
width = 3420
height = 40
offset-x = 10
offset-y = 10
radius = 0.0

fixed-center = true
bottom = true

border-size = 0
line-size = 6

padding-left = 0
padding-right = 1
module-margin-left = 1
module-margin-right = 2

font-0 = monospace:pixelsize=20;4
spacing = 0

background = ${colors.background}
foreground = ${colors.foreground}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

wm-restack = bspwm

modules-left = bspwm
modules-center = date
modules-right = filesystem memory cpu temperature eth

; small bar
[bar/small]
monitor = ${env:MONITOR:DP-4}
width = 1000
offset-x = 1220
height = 40
offset-y = 10

fixed-center = true
bottom = true
radius = 6

padding-left = 0
padding-right = 1
module-margin-left = 1
module-margin-right = 1

font-0 = monospace:pixelsize=20;4
spacing = 0

background = ${colors.background}
foreground = ${colors.foreground}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

wm-restack = bspwm

modules-left = date song_artist
modules-center = bspwm
modules-right = song_title up


[settings]
screenchange-reload = true
compositing-background = source
compositing-foreground = over
pseudo-transparency = false

; modules

[module/bspwm]
type = internal/bspwm

;label-focused = 
;label-focused = 
label-focused = 
;label-focused = %name%
label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-focused-padding = 1

;label-occupied = 
;label-occupied = 
label-occupied = 
;label-occupied = %name%
;label-occupied-underline = ${colors.primary}
label-occupied-foreground = ${colors.primary}
label-occupied-padding = 1

;label-urgent = !
;label-urgent = !
label-urgent = !
;label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

;label-empty = 
;label-empty = 
label-empty = 
;label-empty = %name%
label-empty-padding = 1


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%


[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%


[module/eth]
type = internal/network
interface = enp0s31f6
interval = 2

format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.primary}
label-connected = %local_ip%

format-disconnected =  <label-disconnected>
format-disconnected-foreground = ${colors.alert}
label-disconnected = %ifname%


[module/up]
type = internal/network
interface = enp0s31f6
interval = 1

format-connected-prefix = "inet "
format-disconnected-prefix = ${self.format-connected-prefix}

label-connected = up
label-connected-foreground = ${colors.secondary}

label-disconnected = down
label-disconnected-foreground = ${colors.alert}


[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted-prefix = " "
format-unmounted-prefix = " "
format-mounted-prefix-foreground = ${colors.primary}
format-unmounted-prefix-foreground = ${colors.alert}
label-mounted = %mountpoint%:%percentage_used:3%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.alert}


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-warn-underline = ${colors.alert}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-foreground = ${colors.primary}


[module/date]
type = internal/date
interval = 1

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt =

;format-prefix = ""
;format-prefix-alt = ""
format-prefix-foreground = ${colors.primary}

label = %date% %time%


[module/song_title]
type = custom/script
exec = cat ~/.cache/song_title.txt
interval = 2

format = <label>
format-foregroung = ${colors.primary}
label = %output:0:11:..%

click-left = playerctl play-pause


[module/song_artist]
type = custom/script
exec = cat ~/.cache/song_artist.txt
interval = 2

format = <label>
format-foregroung = ${colors.primary}
label = %output:0:11:..%

click-left = playerctl play-pause
